### ISSUE TITLE
Fail to write and abort

### ISSUE THREAD

**Issue by WebMaestroFr** [WebMaestroFr/rpi-mpeg-ts#2]
After some time, the stream eventually breaks on this error.

```
Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14)

mmal: Failed to write buffer data (3248 from 5160)- aborting
```

**Comment by WebMaestroFr** [comment]
The raspivid process sometimes doesn't hang up on development, and this error may pop up, but not if module doesn't fail. So let's not fail.
